### ISSUE TITLE
yq fails to install in ARM64

### ISSUE THREAD

**Issue by jairov4** [kislyuk/yq#147]
Tried to install under Python 3 in Docker amazonlinux:2.0.20211201.0
```
#0 2.952 Traceback (most recent call last):
#0 2.953   File "/usr/local/bin/pip3.9", line 8, in <module>
#0 2.955     sys.exit(main())
#0 2.957   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 71, in main
#0 2.957     return command.main(cmd_args)
#0 2.957   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 104, in main
#0 2.957     return self._main(args)
#0 2.957   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 221, in _main
#0 2.958     self.handle_pip_version_check(options)
#0 2.958   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 143, in handle_pip_version_check
#0 2.958     session = self._build_session(
#0 2.958   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 87, in _build_session
#0 2.958     session = PipSession(
#0 2.958   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 275, in __init__
#0 2.959     self.headers["User-Agent"] = user_agent()
#0 2.959   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
#0 2.961     linux_distribution = distro.linux_distribution()  # type: ignore
#0 2.961   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
#0 2.961     return _distro.linux_distribution(full_distribution_name)
#0 2.961   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
#0 2.965     self.version(),
#0 2.965   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
#0 2.965     self.lsb_release_attr('release'),
#0 2.965   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
#0 2.965     return self._lsb_release_info.get(attribute, '')
#0 2.966   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
#0 2.967     ret = obj.__dict__[self._fname] = self._f(obj)
#0 2.967   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
#0 2.969     stdout = subprocess.check_output(cmd, stderr=devnull)
#0 2.969   File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
#0 2.970     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 2.970   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
#0 2.972     raise CalledProcessError(retcode, process.args,
#0 2.972 subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
```

**Comment by jairov4** [comment]
🤔 you are right. but still weird, many other hundreds of packages in the same stack had no issue. I will check deeper. anyone knows if this package has any binary dep that leads pip to some confusion?
