### ISSUE TITLE
Can't load a standard yaml file

### ISSUE THREAD

**Issue by rbosse** [kislyuk/yq#48]
I took just a simple yaml and got this error:

$ cat application.yaml | yq .
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\yq.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\yq\__init__.py", line 150, in main
    parser.exit(msg.format(program_name, type(e).__name__, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 23: ordinal not in range(128)

**Comment by kislyuk** [comment]
Thanks for reporting. I'm unable to reproduce this. If you could please supply a file for which this happens and the output of `yq --version`, I can look into this further.

**Comment by kislyuk** [comment]
Closing due to lack of response.
